### ISSUE TITLE
Custom alias not allowed

### ISSUE THREAD

**Issue by Kharg** [dubas-pro/ext-short-url#1]
https://github.com/dubas-pro/ext-short-url/blob/ac44c7ba6178ffde011493dcecfcfa1da63f0fe3/src/files/application/Espo/Modules/DubasShortUrl/Hooks/ShortUrl/GenerateAlias.php#L31

this line is not allowing custom aliases because as soon as you input one it will be overwritten because of this:  $entity->isAttributeChanged('alias')

Removing this part lets you define custom aliases.

**Comment by emillod** [comment]
I'm sorry, just noticed. 
Fixed in the newest version. 

https://github.com/dubas-pro/ext-short-url/releases/tag/1.0.0
