### ISSUE TITLE
The short URL extension no longer works.

### ISSUE THREAD

**Issue by ChrisSka** [dubas-pro/ext-short-url#3]
Through a tip, I was told that the short url no longer works.

I call up a public form via short url, for which I use Public Forms from eblasoft.
If I call up the link normally without the short url, the public form appears as it should.
If I call up the same via the short url, I am taken to the page -> /api/v1/l/
and something with source code formatting only appears in the window.

![image](https://github.com/user-attachments/assets/59189a94-9523-4c00-a623-72e03bff693d)

**Comment by ChrisSka** [comment]
PHP Version: 8.1.30
EspoCRM: 8.4.2

Perhaps this is due to a recent update of EspoCRM.
I use the short URL on a website.
It has worked all the time without any problems.
I only ever had to change the short URL in EspoCRM and didn't have to change anything on the website.
I only became aware of this when I was informed by a customer.

**Comment by ChrisSka** [comment]
For your information:
I have tested the other short URLs and none of them work for me.
All links are redirected to the folder /api/v1/l/ and the image shown above.

Here is an example link:
https://portal.kurtgenussundkeramik.de/link/HK-5206

**Comment by emillod** [comment]
Fixed in the newest version. 
https://github.com/dubas-pro/ext-short-url/releases/tag/1.0.0
